services:
  postgres:
    image: postgres:17
    environment:
      # Default user is postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/greenev-tqs24-25/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    healthcheck:
      test: "curl --fail --silent localhost:8001/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 2s
      retries: 100
      start_period: 2s

    restart: unless-stopped
    networks:
      - backend
    volumes:
      - maven_data:/root/.m2

  frontend:
    build:
      context: ./frontend/green-ev
      dockerfile: Dockerfile.prod

    image: ghcr.io/greenev-tqs24-25/frontend:latest
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontend

  proxy:
    image: nginx:latest
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
      - frontend
    restart: unless-stopped
    volumes:
      - ./proxy/prod.conf:/etc/nginx/conf.d/default.conf

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./k6/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH="true"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./k6/grafana:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    networks:
      - backend

  k6:
    image: grafana/k6:0.54.0
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/k6
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    command: run -o experimental-prometheus-rw /k6/spike-test.js
    networks:
      - backend
  stripe:
    image: stripe/stripe-cli:latest
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env.prod
    command: listen --forward-to http://localhost/api/v1/public/payment/webhook
    network_mode: "host"

networks:
  backend:
  frontend:

volumes:
  maven_data:
  pg_data:
  grafana_data:
